# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riq_4G5rADlKz0WN9yvr557F1ext5ZdA
"""



"""1. Understanding Variables

a) Define a variable in python.provide an example  of how to create a variable that stores your name.
  Ans: It's that named location in memory that stores and manipulates data values like string,tuple etc.
   name = "nisarga" , name is a variable
b) What is difference between a variable and a constant?can we have constants in python?
 Ans: Variable : variable changes it's value depending upon equation.
      Constant:  It does not change it's value as the equation is solved.

2. Working with data types

a) Create variables of the following types in python:
   1. Integer
   2. Float
   3. String
   4. Boolean

1. Integer
"""

year = 2025
print(year)

"""  2. Float"""

weight = 3.14
print(weight)

""" 3. String"""

name = "nisarga"
print(name)

"""4 . Boolean"""

my_variable = True
print(my_variable)

"""2 b) Write a python script to display the type of each variable you created.
   
"""

r = 4
s = 7
y = "Hello, Python!"
my_variable = True
my_list = [2,3,4]
my_tuple = (5,6,7)
my_dict = {"name": "nisarga", "age": 21}
print("type of r:", type(r))
print("type of s:", type(s))
print("type of y:", type(y))
print("type of my_variable:", type(my_variable))
print("type of my_list:", type(my_list))
print("type of my_tuple:", type(my_tuple))
print("type of my_dict:", type(my_dict))

"""3. Arithmetic Operations

a) explain the following arithmetic operations with examples:
  1. Addition('+')
  2. Subtraction('-')
  3. Multipication('*')
  4. Division('/')
  5. floor division('//')
  6. Modulus('%')
  7. Expoentiation('')

1. Addition
"""

a = 14
b = 10
print(a+b)

"""2. Subtraction"""

a = 14
b = 10
print(a-b)

"""3. Multiplication"""

a = 14
b = 10
print(a*b)

"""4. Division"""

a = 20
b = 2
print(a/b)

"""5. Floor Division"""

a = 110.89
b = 20.23
print(a//b)

"""6. Modulus"""

a = 56
b = 67
print(a%b)

"""7. Exponentiation"""

a =  120
b = 2
print(a**b)

"""b) Write a python script to calculate the area of a rectangle using variables 'length' and 'width' with value 5and10,respectively.use the multiplication operator."""

length = 5
width = 10
area = length*width
print("area of the rectangle:",area)

"""4. comparision and logical operators

a) Explain the following comparison operators with examples:
 1. Equal to('==')
 2. Not equal('!=')
 3. Greater than('<')
 4. less than('>')
 5. greater than or equal to('>=")
 6. less than or equal to('<=')

1. Equal to
"""

a = 2
b = 2
print(a==b)

"""2. Not equal to"""

a = 3
b = 4
print(a!=b)

"""3. Greater than"""

a = 10
b = 8
print(a>b)

"""4. Less than"""

a = 10
b = 41
print(a<b)

"""5. Greater than or equal to"""

a = 400
b = 300
print(a>=b)

"""6. less than or equal to"""

a = 500
b = 1000
print(a<=b)

"""b) Using logical operations ('and','or','not'),write a python script that checks if a number is positive andeven"""

num = int(input("enter a number:"))
if num>0 and num%2 == 0:
   print("the number is positive and even.")
else:
    print("the number is not positive and even.")

"""5. Type casting in Python

a)What is type casting?Explain the difference between implicit and explicit type casting with examples.
 Ans: It convert variable data type into certain data type.

   Implicit:value of one data type is automatically converted to another data type, without explicit casting.
   
   Explicit: When a value is explicitly converted from one data type to another using a casting operator.

b) Write a python script that:
 1. Converts a float to an integer.
 2. Converts an integer to a string.
 3. Converts a string to a float

1. Converts a float to an integer.
"""

float_num = 3.14
int_num = int(float_num)
print(int_num)

"""2. Converts an integer to a string."""

int_num = 10
str_num = str(int_num)
print(str_num)

"""3. Converts a string to a float"""

str_num = 200
float_num = float(str_num)
print(float_num)

"""6. Write a python script that  asks the user to input tow numbers and then:

a. Add the two numbers and prints the result.

b. Subtracts the second number from the first and prints the results.

c. Multiplies the two numbers and prints the results.

d. divides the first number by the second and prints the result(handle division by zero).

e. converts the sum of the numbers to a string and prints the type og the results.

1. Add the two numbers and prints the result.
"""

num1 = 500
num2 = 1000
result = num1 + num2
print("the result is :",result)

"""2. Subtracts the second number from the first and prints the results."""

num1 = 200
num2 = 100

result = num1 - num2
print("the result is:",result)

"""3. Multiplies the two numbers and prints the results."""

num1 = 200
num2 = 100
result = num1 * num2
print("the result is:",result)

"""4. divides the first number by the second and prints the result(handle division by zero)."""

num1 =  10.0
num2 = 0.0
try:
    result = num1 / num2
    print("The result is:", result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

"""5. converts the sum of the numbers to a string and prints the type of the results."""

num1 = 5.0
num2 = 3.5
sum_result = num1 + num2
sum_str = str(sum_result)
print("The sum as a string is:", sum_str)
print("The type of the result is:", type(sum_str))